// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAvtVNt_YeAHB-TzMYA9Xf8vLH53Glqqw',
    appId: '1:19465852024:android:0bd01b59b3866528c1898d',
    messagingSenderId: '19465852024',
    projectId: 'inventory-management-fc586',
    storageBucket: 'inventory-management-fc586.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC216GnXjW9otQdDU9907NXY4Q2Elkrj34',
    appId: '1:19465852024:ios:d1cf890b4d8d3330c1898d',
    messagingSenderId: '19465852024',
    projectId: 'inventory-management-fc586',
    storageBucket: 'inventory-management-fc586.appspot.com',
    iosBundleId: 'com.example.inventorymanagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-D8iumSFE6U0PYn-J5vpTg4_oYPY6O8A',
    appId: '1:19465852024:web:de543461a2fe51c2c1898d',
    messagingSenderId: '19465852024',
    projectId: 'inventory-management-fc586',
    authDomain: 'inventory-management-fc586.firebaseapp.com',
    storageBucket: 'inventory-management-fc586.appspot.com',
    measurementId: 'G-GJFD2MCPCS',
  );
}
